# -*- coding: utf-8 -*-
"""Scipy_tut

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CPkePMcskte7iL5peZyznnbgW2_JXtsF

# SciPy Tutorial 
06.01.2020
"""

import scipy.integrate

#f = lambda x:12*x
#i = scipy.integrate.quad(f,0,1)
#print(i)
"""
# Double Integral

f = lambda x, y : 12*x
g = lambda x : 0
h = lambda y : 1
i = scipy.integrate.dblquad(f, 0, 0.5, g, h)
print(i)
"""

# Triple Integral
from scipy import integrate
f = lambda z,y,x : 12*x

integrate.tplquad(f,0,0.5,lambda x:0, lambda x:1,lambda x,y:0, lambda x,y:3)

"""rv_histogram"""

from scipy import stats
import numpy as np
import matplotlib.pyplot as plt


data = scipy.stats.norm.rvs(size=1000, loc=0, scale=1.0, random_state=123)
hist = np.histogram(data, bins=100)
hist_dist = scipy.stats.rv_histogram(hist)
X = np.linspace(-5.0, 5.0, 100)
plt.hist(data, density=True, bins=100)
plt.plot(X, hist_dist.pdf(X), label="PDF")
plt.plot(X, hist_dist.cdf(X), label="CDF")